#!/usr/bin/env python3
"""gen_fold_loc.py -- writes tdl_loc_fold.xdc for the FOLD build.

Both chains move up 12 rows (CARRY4 #0 at Y42) so the fold B..E (taps 32..167,
CARRY4 #8..#41) sits at Y50..Y83, inside clock region rows Y50..Y99. The
counting section crosses Y100; only sparse taps live there, so that wide bin
never enters a lap.

Locked, exactly like tdl_loc.xdc: every CARRY4, and every sampled tap's first
flop (tap_reg) in the SAME slice as its CARRY4 on BEL {A,B,C,D}FF, so the
capture skew is identical across taps. The return LUT is not locked: a CARRY4
S input can only come from its own slice's LUT, so Vivado has no choice;
check_placement_fold.tcl verifies it landed in the B slice.

Run from code/:   python gen_fold_loc.py      -> tdl_loc_fold.xdc
"""
LAUNCH_W, FOLD_W, NCNT, CNT_STEP, NUM_C4 = 32, 136, 7, 30, 88
Y0 = 42
CHAINS = [("chan_a", 37), ("chan_b", 48)]
FF = ["AFF", "BFF", "CFF", "DFF"]

def sampled_to_tap(j):
    return j if j < LAUNCH_W + FOLD_W else LAUNCH_W + FOLD_W + CNT_STEP * (j - LAUNCH_W - FOLD_W)

L = ["# =============================================================================",
     "# tdl_loc_fold.xdc -- GENERATED by gen_fold_loc.py. FOLD builds only.",
     "# Enable this file and DISABLE tdl_loc.xdc (baseline) in the same build.",
     f"#   chan_a CARRY4 SLICE_X37 Y{Y0}..Y{Y0+NUM_C4-1}, chan_b SLICE_X48 same rows",
     f"#   B = CARRY4 #8 (Y50), fold CARRY4 #8..#41 (Y50..Y83), region X1Y1",
     f"#   sampled taps: 0..{LAUNCH_W+FOLD_W-1} plus {LAUNCH_W+FOLD_W}+{CNT_STEP}j, j<{NCNT}",
     "# ============================================================================="]
for name, x in CHAINS:
    L.append(f"# ============ {name} : CARRY4 delay line ({NUM_C4} cells) ============")
    for n in range(NUM_C4):
        c = f"core/{name}/tdl_inst/g_c4[{n}].u_c4"
        L.append(f"set_property LOC SLICE_X{x}Y{Y0+n}   [get_cells {{{c}}}]")
        L.append(f"set_property BEL SLICEL.CARRY4  [get_cells {{{c}}}]")
    # Return LUT: force it into the B slice (CARRY4 #8), A6LUT, so its O6 feeds
    # S0 directly. Left free, the placer parked it ~15 rows away and inserted a
    # pass-through LUT in the B slice: a longer return path than the probe measured.
    L.append(f"# ============ {name} : return LUT in the B slice ============")
    L.append(f"set_property BEL SLICEL.A6LUT  [get_cells {{core/{name}/tdl_inst/u_ret}}]")
    L.append(f"set_property LOC SLICE_X{x}Y{Y0+8}   [get_cells {{core/{name}/tdl_inst/u_ret}}]")
    L.append(f"# ============ {name} : tap_reg capture flops ({LAUNCH_W+FOLD_W+NCNT} cells) ============")
    for j in range(LAUNCH_W + FOLD_W + NCNT):
        t = sampled_to_tap(j)
        c = f"core/{name}/tap_snap_inst/tap_reg_reg[{j}]"
        L.append(f"set_property LOC SLICE_X{x}Y{Y0 + t // 4}   [get_cells {{{c}}}]")
        L.append(f"set_property BEL SLICEL.{FF[t % 4]}     [get_cells {{{c}}}]")
open("tdl_loc_fold.xdc", "w").write("\n".join(L) + "\n")
print(f"tdl_loc_fold.xdc: {2 * len(CHAINS) * (NUM_C4 + LAUNCH_W + FOLD_W + NCNT + 1)} LOC/BEL lines")
